modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/Ezzenix/SmoothGui/issues"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayURL = "https://modrinth.com/mod/smooth-gui"
modUrl = "https://modrinth.com/mod/smooth-gui"
displayName = "${name}"
authors = "Ezzenix"
description = '''
${description}
'''
logoFile = "${id}/icon.png"
logoBlur = false

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"
